title: 'pdb-tools'
headline: ''

logo: /logo/pdb-tools.png
show_downloads: true
description: 'A swiss army knife for editing PDB files.'
theme: jekyll-theme-minimal
github:
  zip_url: https://github.com/haddocking/pdb-tools/archive/2.0.0-beta.3.zip
  tar_url: https://github.com/haddocking/pdb-tools/archive/2.0.0-beta.3.tar.gz